[project]
name = "helmet-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hamed", email = "mah2mdahm3d121@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.0",
    "pillow>=12.3.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.54.0",
]

[project.scripts]
helmet-detect = "helmet_detect:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
